M48
; DRILL file {KiCad 7.0.9} date Wed Apr 10 12:45:51 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-10T12:45:51-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
%
G90
G05
T1
X2.0866Y-2.0866
X2.0866Y-5.3937
X5.0Y-2.0866
X5.0Y-5.3937
T0
M30
